apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: web:latest
        name: php
        imagePullPolicy: IfNotPresent
